### PR TITLE
`ivadomed` configs for training spinal cord segmentation

### PR DESCRIPTION
**Pull request by uzaymacar**
This PR adds the ivadomed config file ~~`train_scseg.json` and `test_scseg.json`~~ `seg_sc.json` (only kept one config file as per [this comment](https://github.com/ivadomed/model_seg_ms_mp2rage/pull/19#pullrequestreview-835786601)) for training and testing a UNet3D model for spinal cord (SC) segmentation.

In training, we will utilize the newly implemented augmentations in ivadomed (as described in #16)  just as in #11.

To Reproduce
----

**0. Make sure you have the following dependencies:**
* `sct`=5.4.0
* `ivadomed`=(git-master-93ba03df76d229d8a190c694f757da6c00efa545)

**1. Clone the repository:** 
```
git clone https://github.com/ivadomed/model_seg_ms_mp2rage.git
cd model_seg_ms_mp2rage
```
**2. Clone the data:**
```
git clone git@data.neuro.polymtl.ca:datasets/basel-mp2rage
cd basel-mp2rage
git annex get .
cd ..
```
**3. Preprocess the data:**
```
sct_run_batch -script preprocessing/preprocess_data.sh -path-data basel-mp2rage -path-output basel-mp2rage-preprocessed -jobs <JOBS>
``` 
***Optional*: Run quality-control (QC) on preprocessed data:**
```
python preprocessing/qc_preprocess.py -s basel-mp2rage-preprocessed
```
**4. Run inference on the models (see below for a longer description of models):**
```
git checkout um/ivadomed_scseg_training
cp -r ~/duke/temp/uzay/saved_models_basel/seg_sc_output .

# Training was carried out with: ivadomed --train -c config/seg_sc.json

# Test
ivadomed --test -c config/seg_sc.json

# Segment entire dataset
ivadomed --segment -c config/seg_sc.json
```

### CODE REVIEW

**Review by jcohenadad — COMMENTED** [review]
Do we really need two JSON files? The only difference between the two is the 'command' key, right? Having two files adds more burden on the maintenance, and I _think_ by calling ivadomed with the CLI flag 'test/train' you can superseed the JSON file

**Comment by uzaymacar** [comment]
Yeah agreed. I only did two JSON files so that it is parallel to [lesion segmentation config files](https://github.com/ivadomed/model_seg_ms_mp2rage/tree/um/baseline_ivadomed_training/config) where we need two JSON files as the `"target_suffix"` key is changed during training and testing. The alternative would be to manually change this key before training and testing but that is not so clean.

I can fix this branch so that there is only one config file, but then the question is: is it OK for SC segmentation to have one config file whereas the lesion segmentation has two config files. It might be difficult to interpret for someone else coming to the repo. Perhaps adding documentation on why we have two config files for that case will solve this issue?

**Comment by jcohenadad** [comment]
> whereas the lesion segmentation has two config files.

i would also only keep one config file on the other repos

**Comment by uzaymacar** [comment]
Sorry coming back to this again @jcohenadad, I am not sure how I can keep one config file for lesion segmentation. Just to be clear, the files we are talking about are [`train_randomrater.json`](https://github.com/ivadomed/model_seg_ms_mp2rage/blob/um/baseline_ivadomed_training/config/train_randomrater.json), [`test_randomrater_on_rater1.json`](https://github.com/ivadomed/model_seg_ms_mp2rage/blob/um/baseline_ivadomed_training/config/test_randomrater_on_rater1.json), and [`test_randomrater_on_rater2.json`](https://github.com/ivadomed/model_seg_ms_mp2rage/blob/um/baseline_ivadomed_training/config/test_randomrater_on_rater2.json). Only thing that comes to mind is to keep the training config (renaming it accordingly), and add a line or two on README that describes how to modify the `"target_suffix"` for testing.

**Comment by jcohenadad** [comment]
> Sorry coming back to this again @jcohenadad, I am not sure how I can keep one config file for lesion segmentation. Just to be clear, the files we are talking about are train_randomrater.json, test_randomrater_on_rater1.json, and test_randomrater_on_rater2.json. Only thing that comes to mind is to keep the training config (renaming it accordingly), and add a line or two on README that describes how to modify the "target_suffix" for testing.

Ah, I see, I thought we were talking about other 'two files' (train and test). In any case, if there is only one or two keywords to change, then yes, i would suggest to change it on the syntax rather than on the JSON. 

Right now, we are prototyping, so we have more flexibility in terms of version tracking the JSOn files. As long as everything is properly documented for your experiments (so we can come back to them in the future), you can use the syntax.

The JSON will be really useful once the model is put into production (ie: we can use a one liner to reproduce the training)

**Comment by uzaymacar** [comment]
As shown in the [progress report](https://docs.google.com/presentation/d/1LpeKebhNBH-JC5ht1g8UOm8Zi9tRqgDZ4oMnTi7I9Uo/edit?usp=sharing) (see the *Spinal Cord Segmentation* section) for last week models trained with the current config file had a discrepancy between training and test scores. We identified this is most likely due to the usage of a center-crop of `(128, 128, 128)`. This value was indeed not well advised. The latest commit [8d4ca8f](https://github.com/ivadomed/model_seg_ms_mp2rage/pull/19/commits/8d4ca8f1527bfd8413c38a05f97d0d4a926af1a9) modifies the preprocessing QC script s.t. we log sizes of the original images. 

When we run this latest QC, we see that all 30 subject images have a size of `(240, 256, 176)` and we will be updating the center-crop parameter accordingly.

**Comment by uzaymacar** [comment]
The latest commit [cb8a25c](https://github.com/ivadomed/model_seg_ms_mp2rage/pull/19/commits/cb8a25c9bbeab38b1d61cc241b84eb9e4fab2288): 
* fixes the data path after the changes in #24
* changes the center crop to `(256, 256, 256)`

Note that the center crop size is larger than the size of the original images `(240, 256, 176)` as reported above. This is because `ivadomed` requires input shape of each dimension to be a **multiple of length plus 2 * padding and a multiple of 16** where the length in our case is `128` per axis as given by the `length_3D` parameter under `Modified3DUNet`.

**Comment by jcohenadad** [comment]
> This is because ivadomed requires input shape of each dimension to be a multiple of length plus 2 * padding and a multiple of 16 where the length in our case is 128 per axis as given by the length_3D parameter under Modified3DUNet.

Hum, is that a burden? Should we consider alleviating this limitation?

**Comment by uzaymacar** [comment]
> Hum, is that a burden? Should we consider alleviating this limitation?

I don't think its a problem for this project, but I think at the very least it is an issue-worthy topic! I have opened one in ivadomed: https://github.com/ivadomed/ivadomed/issues/1022.

**Comment by uzaymacar** [comment]
The latest commit [32a1108](https://github.com/ivadomed/model_seg_ms_mp2rage/pull/19/commits/32a110831b710a73eba5453f4291a9b67c428875):
* increases length and stride to `(256, 256, 256)` such that the entire volume (i.e. the full brain image) is the input to model
* batch size is decreased from `4` to `2` in order to decrease GPU memory usage
* random gamma parameters are updated
* added random bias field and random blur data augmentations (more context at #16)
* renames the file to be consistent across other branches

This config / latest model achieves a test Dice score of `0.9473`. More info can be found in this week's [progress report](https://docs.google.com/presentation/d/1xgR1ZBwQx3jXfWUqWtTvixTIwCiaohkpkm2vCwTxJlw/edit?usp=sharing). Additionally, the main comment of this PR is updated with steps to use / reproduce the model.

**Comment by uzaymacar** [comment]
As per the discussion in the meeting, we might want to check whether `(256, 256, 256)` input shapes have any limitations in terms of RAM etc. in inference.

**Comment by uzaymacar** [comment]
The latest commit [c8359b1](https://github.com/ivadomed/model_seg_ms_mp2rage/pull/19/commits/c8359b1f5e7592ada4802ca52ca9d0d5e22133a1) changes slice axis to `sagittal` as discussed in #26. Note that the center-crop, length, and stride size params stay the same here as it is `(256, 256, 256)`, i.e. same size in all axes. It also reduces the number of epochs from `500` to `200` because we see a faster convergence in spinal cord segmentation compared to lesion segmentation.

Subsequently, the models mentioned [here](https://github.com/ivadomed/model_seg_ms_mp2rage/pull/19#issue-1083250980) are updated and new results are consistent with the previous results. The latest model achieves a test Dice score of `0.9511`.

**Pull request merged**
